#!/usr/bin/env python3
"""Build targeted Serper queries from NY DOS registry seed names for one county.

Adapted from state_scrapers/fl/scripts/fl_build_sunbiz_county_queries.py with
NY-specific phrasing: coops use proprietary leases + offering plans, condos use
declarations, HOAs use covenants. Queries OR all three so a single template
covers all three governance forms.

Usage:
    python state_scrapers/ny/scripts/ny_build_county_queries.py \
        --county "Kings" \
        --output benchmark/results/ny_registry_kings/queries.txt \
        [--max-queries-per-county 1500] \
        [--offset 0]

Note: NY borough names go in as `New York`, `Kings`, `Queens`, `Richmond`,
`Bronx` (the legal county names), not `Manhattan`/`Brooklyn`/`Staten Island`.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SEED_PATH = ROOT / "state_scrapers" / "ny" / "leads" / "ny_registry_seed.jsonl"

STRIP_RE = re.compile(
    r",?\s+(INC\.?|LLC\.?|L\.L\.C\.?|CORP\.?|CORPORATION|LTD\.?|"
    r"P\.?C\.?|P\.?A\.?|L\.?P\.?)\s*$",
    re.IGNORECASE,
)
TRAIL_RE = re.compile(r"[\s,;.]+$")

MIN_NAME_LEN = 10  # NYC coops have short addresses; lower than FL's 12


def clean_name(raw: str) -> str:
    name = raw.strip()
    # Strip multiple trailing legal suffixes (e.g., "OWNERS CORP, INC.")
    for _ in range(3):
        name = STRIP_RE.sub("", name)
    name = TRAIL_RE.sub("", name)
    return name


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate NY-DOS-seeded HOA queries for one NY county."
    )
    ap.add_argument(
        "--county", required=True,
        help="NY legal county name (e.g. 'Kings', 'New York', 'Queens', 'Westchester')",
    )
    ap.add_argument("--output", "-o", help="Output queries file (default stdout)")
    ap.add_argument(
        "--max-queries-per-county", type=int, default=1500,
        help="Cap total queries emitted (default 1500).",
    )
    ap.add_argument(
        "--offset", type=int, default=0,
        help="Skip this many seed names before starting (paginated batches).",
    )
    args = ap.parse_args()

    county = args.county.strip()
    county_lower = county.lower()

    names: list[str] = []
    with open(SEED_PATH) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if (row.get("county") or "").lower() != county_lower:
                continue
            raw = row.get("name", "")
            cleaned = clean_name(raw)
            if len(cleaned) >= MIN_NAME_LEN:
                names.append(cleaned)

    if not names:
        print(f"WARNING: no seed names for county '{county}'", file=sys.stderr)

    names = names[args.offset:]
    max_q = args.max_queries_per_county

    lines: list[str] = [
        f"# NY Driver A — county={county} offset={args.offset}"
        f" total_seeds={len(names)+args.offset}"
        f" generated by ny_build_county_queries.py"
    ]
    count = 0
    for name in names:
        if count >= max_q:
            break
        # Query 1: filetype:pdf direct hit (highest precision)
        lines.append(f'"{name}" "New York" filetype:pdf')
        count += 1
        if count >= max_q:
            break
        # Query 2: governing-doc keyword catch — OR all three NY forms
        lines.append(
            f'"{name}" "New York" '
            f'"declaration" OR "by-laws" OR "by laws" OR '
            f'"offering plan" OR "proprietary lease" OR "covenants"'
        )
        count += 1

    body = "\n".join(lines) + "\n"
    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        Path(args.output).write_text(body)
        print(f"wrote {count} queries to {args.output}", file=sys.stderr)
    else:
        print(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
