#!/usr/bin/env python3
"""Driver A — Build targeted Serper queries from CA registry HOA seed
names for one county.

Mirrors state_scrapers/fl/scripts/fl_build_sunbiz_county_queries.py.

Usage:
    python state_scrapers/ca/scripts/ca_build_corp_county_queries.py \
        --county los-angeles \
        --output benchmark/results/ca_corp_los-angeles/queries.txt \
        [--max-queries-per-county 1500] \
        [--offset 0]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
REGISTRY_PATH = ROOT / "data" / "ca_registry_hoas.jsonl"

MIN_NAME_LEN = 12


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate corp-name-seeded HOA queries for one CA county.")
    ap.add_argument("--county", required=True, help="County slug, e.g. los-angeles")
    ap.add_argument("--output", "-o", help="Output file path (default: stdout)")
    ap.add_argument("--max-queries-per-county", type=int, default=1500)
    ap.add_argument("--offset", type=int, default=0)
    ap.add_argument(
        "--registry",
        default=str(REGISTRY_PATH),
        help="Path to ca_registry_hoas.jsonl",
    )
    args = ap.parse_args()

    county_slug = args.county.lower().strip()

    names: list[str] = []
    with open(args.registry) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if (row.get("county") or "").lower() == county_slug:
                cleaned = (row.get("name_clean") or "").strip()
                if len(cleaned) >= MIN_NAME_LEN:
                    names.append(cleaned)

    if not names:
        print(f"WARNING: no names found for county '{county_slug}'", file=sys.stderr)

    names = names[args.offset:]
    max_q = args.max_queries_per_county

    lines: list[str] = [
        f"# CA Driver A — county={county_slug} offset={args.offset}"
        f" generated by ca_build_corp_county_queries.py"
    ]
    count = 0
    used_names = 0
    for name in names:
        if count >= max_q:
            break
        # Q1: filetype:pdf direct
        lines.append(f'"{name}" "California" filetype:pdf')
        count += 1
        if count >= max_q:
            used_names += 1
            break
        # Q2: document-keyword search (CA-specific terms included)
        lines.append(
            f'"{name}" "California" "declaration" OR "covenants" OR "CC&R" OR "Davis-Stirling"'
        )
        count += 1
        used_names += 1

    out_text = "\n".join(lines) + "\n"

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(out_text)
        print(
            f"county={county_slug} names_in_county={len(names)+args.offset}"
            f" names_used={used_names} queries_written={count} -> {out_path}",
            file=sys.stderr,
        )
    else:
        sys.stdout.write(out_text)
        print(
            f"county={county_slug} names_in_county={len(names)+args.offset}"
            f" names_used={used_names} queries_written={count}",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
