#!/usr/bin/env python3
"""Build targeted Serper queries from FL Sunbiz HOA seed names for one county.

Usage:
    python scripts/fl_build_sunbiz_county_queries.py \
        --county miami-dade \
        --output benchmark/results/fl_sunbiz_miami-dade/queries.txt \
        [--max-queries-per-county 1500] \
        [--offset 0]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SUNBIZ_PATH = ROOT / "data" / "fl_sunbiz_hoas_geocoded.jsonl"

# Strip these suffixes before quoting the name.
STRIP_RE = re.compile(
    r",?\s+(INC\.?|LLC\.?|CORP\.?|LTD\.?|L\.L\.C\.?)\s*$",
    re.IGNORECASE,
)
# Strip trailing punctuation/whitespace after suffix removal.
TRAIL_RE = re.compile(r"[\s,;.]+$")

MIN_NAME_LEN = 12  # skip names shorter than this after cleaning


def clean_name(raw: str) -> str:
    name = raw.strip()
    name = STRIP_RE.sub("", name)
    name = TRAIL_RE.sub("", name)
    return name


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate Sunbiz-seeded HOA queries for one FL county.")
    ap.add_argument("--county", required=True, help="County slug, e.g. miami-dade")
    ap.add_argument(
        "--output", "-o",
        help="Output file path (default: stdout)",
    )
    ap.add_argument(
        "--max-queries-per-county", type=int, default=1500,
        help="Maximum number of queries to emit (default 1500).",
    )
    ap.add_argument(
        "--offset", type=int, default=0,
        help="Skip this many HOA names before starting (for paginated batches).",
    )
    args = ap.parse_args()

    county_slug = args.county.lower().strip()

    # Load and filter.
    names: list[str] = []
    with open(SUNBIZ_PATH) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if (row.get("county") or "").lower() == county_slug:
                raw = row.get("name", "")
                cleaned = clean_name(raw)
                if len(cleaned) >= MIN_NAME_LEN:
                    names.append(cleaned)

    if not names:
        print(f"WARNING: no names found for county '{county_slug}'", file=sys.stderr)

    # Apply offset, then generate up to 2 queries per HOA until we hit the cap.
    names = names[args.offset:]
    max_q = args.max_queries_per_county

    lines: list[str] = [
        f"# FL Sunbiz Driver A — county={county_slug} offset={args.offset}"
        f" generated by fl_build_sunbiz_county_queries.py"
    ]
    count = 0
    used_names = 0
    for name in names:
        if count >= max_q:
            break
        # Query 1: filetype:pdf direct
        lines.append(f'"{name}" "Florida" filetype:pdf')
        count += 1
        if count >= max_q:
            used_names += 1
            break
        # Query 2: document-keyword search
        lines.append(f'"{name}" "Florida" "declaration" OR "covenants" OR "bylaws"')
        count += 1
        used_names += 1

    out_text = "\n".join(lines) + "\n"

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(out_text)
        print(
            f"county={county_slug} names_in_county={len(names)+args.offset}"
            f" names_used={used_names} queries_written={count} -> {out_path}",
            file=sys.stderr,
        )
    else:
        sys.stdout.write(out_text)
        print(
            f"county={county_slug} names_in_county={len(names)+args.offset}"
            f" names_used={used_names} queries_written={count}",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
